[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=/usr/bin/mold",
    "-C", "target-cpu=native"
]

[build]
incremental = true
jobs = 24
rustc-wrapper = "sccache"

[term]
verbose = false
